### ISSUE TITLE
Start time

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [PabloLec/website-to-gif#22]
Can you include that the first X screenshots will be skipped?
I know there is a scroll position, but having a page without scrolling does the trick work?
If yes please update the docs.

Wonderfull project :-)

**Comment by NilsBaumgartner1994** [comment]
Problem is, that a pages takes a bit to load.
At the beginning there is a ugly jump.

![Demo](https://github.com/NilsBaumgartner1994/RaidersOfStorm/blob/main/docs/gif/traveling_example.gif?raw=true)

**Comment by PabloLec** [comment]
Hello @NilsBaumgartner1994  and sorry for the delayed response.

I had not considered your specific use case. What we ultimately need is an option for pages without scroll, which includes the number of frames and the time per frame. We should also have an option (which could also be available for pages with scroll) to wait for x seconds at the start of the job.

Does this seem correct to you? Please let me know if you are still experiencing this problem and if you have any other considerations for your use case.

**Comment by NilsBaumgartner1994** [comment]
Hello, Yes that would fit my case, just to let the SPA load a moment before the recording begins :-)Beste Grüße,Nils BaumgartnerAm 07.05.2023 um 10:50 schrieb Pablo Lecolinet ***@***.***>:﻿
Hello @NilsBaumgartner1994  and sorry for the delayed response.
I had not considered your specific use case. What we ultimately need is an option for pages without scroll, which includes the number of frames and the time per frame. We should also have an option (which could also be available for pages with scroll) to wait for x seconds at the start of the job.
Does this seem correct to you? Please let me know if you are still experiencing this problem and if you have any other considerations for your use case.

**Comment by PabloLec** [comment]
Hi @NilsBaumgartner1994 ! 
I found some time this morning to implement the feature. So now it's possible to capture a page without scrolling and set an initial delay. 
You can find an example in the README and also take a look at https://github.com/PabloLec/website-to-gif/blob/main/.github/workflows/update_demo_gifs.yml for inspiration. I also took the opportunity to reformat the list of possible inputs in the README and present them in a table. It should be clearer if you haven't used the action yet. 

Let me know if anything is wrong, and make sure to use the latest version of the action, 2.1.0. 
Have a great day!

**Comment by NilsBaumgartner1994** [comment]
Thank you very much :-)I believe your tool fulfills such a basic need, that I hope lot more people will useBeste Grüße,Nils BaumgartnerAm 08.05.2023 um 11:24 schrieb Pablo Lecolinet ***@***.***>:﻿
Hi @NilsBaumgartner1994 !
I found some time this morning to implement the feature. So now it's possible to capture a page without scrolling and set an initial delay.
You can find an example in the README and also take a look at https://github.com/PabloLec/website-to-gif/blob/main/.github/workflows/update_demo_gifs.yml for inspiration. I also took the opportunity to reformat the list of possible inputs in the README and present them in a table. It should be clearer if you haven't used the action yet.
Let me know if anything is wrong, and make sure to use the latest version of the action, 2.1.0.
Have a great day!
